//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuyAntiquesStore2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemMaster()
        {
            this.ItemDiscounts = new HashSet<ItemDiscount>();
            this.ItemDiscounts1 = new HashSet<ItemDiscount>();
        }
    
        public int itemId { get; set; }
        public string itemName { get; set; }
        public string itemDescription { get; set; }
        public float itemWeight { get; set; }
        public int itemAge { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public System.DateTime addedDate { get; set; }
        public string currencyCode { get; set; }
        public int categoryId { get; set; }
        public string itemImage { get; set; }
        public Nullable<byte> boughtFromCustomer { get; set; }
        public int customerID { get; set; }
        public int quantity { get; set; }
        public float itemPrice { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemDiscount> ItemDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemDiscount> ItemDiscounts1 { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
