//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuyAntiquesStore2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderPayments = new HashSet<OrderPayment>();
        }
    
        public int orderID { get; set; }
        public int customerID { get; set; }
        public int orderNumber { get; set; }
        public int paymentType { get; set; }
        public double tax { get; set; }
        public double totalPrice { get; set; }
        public double subtotal { get; set; }
        public string shippingAddress { get; set; }
        public System.DateTime orderDateTime { get; set; }
    
        public virtual Order Order1 { get; set; }
        public virtual Order Order2 { get; set; }
        public virtual Order Order11 { get; set; }
        public virtual Order Order3 { get; set; }
        public virtual Order Order12 { get; set; }
        public virtual Order Order4 { get; set; }
        public virtual Order Order13 { get; set; }
        public virtual Order Order5 { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPayment> OrderPayments { get; set; }
    }
}
