//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuyAntiquesStore2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public int paymentID { get; set; }
        public string paymentType { get; set; }
        public int orderID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderPayment OrderPayment1 { get; set; }
        public virtual OrderPayment OrderPayment2 { get; set; }
    }
}
